# Generated by Django 4.2.7 on 2023-12-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usercourse_remove_course_language_delete_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
